# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: seeeduino_xiao_ble
    shield: dokodemo_left rgbled_adapter
    artifact-name: dokodemo_left

  - board: seeeduino_xiao_ble
    shield: dokodemo_right rgbled_adapter
    artifact-name: dokodemo_right

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_xiao

  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset_nice_nano

  ## To build with ZMK Studio support, uncomment the following block
  ## by removing the leading '#' from each line.

  #  - board: seeeduino_xiao_ble
  #    shield: dokodemo_left rgbled_adapter
  #    snippet: studio-rpc-usb-uart
  #    cmake-args: -DCONFIG_ZMK_STUDIO=y
  #    artifact-name: dokodemo_left_with_studio

  ## See ZMK documentation on how to build and flash the firmware for dongle mode.
  ## The "board" for the dongle can be anything ZMK supports.

  - board: nice_nano
    shield: dokodemo_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: dokodemo_dongle_with_studio

  - board: seeeduino_xiao_ble
    shield: dokodemo_left rgbled_adapter
    snippet: dokodemo-left-as-peripheral
    artifact-name: dokodemo_left_as_peripheral
